-- AlterTable
ALTER TABLE "users" ADD COLUMN     "publishMessageAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "birthdayAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "birthdayAt" SET DATA TYPE TIMESTAMP;
